### ISSUE TITLE
White Supremacy on GitHub

### ISSUE THREAD

**Issue by unityblows** [StringVar/.emacs.d#8]
It appears this repository has some troubling themes in it. In various points throughout, allusions to white supremacy are made. Please remove these as it creates a toxic environment on GitHub.
![image](https://user-images.githubusercontent.com/52715589/69192553-10dc9680-0ae2-11ea-98db-98946225abfd.png)

**Comment by StringVar** [comment]
Making an account just to harass me is quite annoying. Consider making another as you have been blocked and reported. Please just be respectful and never ever make these kinds of claims on the internet. By doing this kind of harassment you make a toxic environment on github.

As public statement: I absolutely hate Hitler for the atrocities that he committed. Personally Hitler has affected my family by having them flee from Poland and Austria once the war started. 

For anyone reviewing these claims you can search repo commits in the search bar. You will easily  find that these claims are false.

https://github.com/search?q=user%3AStringVar+repos%3AStringVar%2F.emacs.d+Hitler&type=Commits
0 results

search by repo "repo:StringVar/.emacs.d Hitler did nothing wrong" 

or by author:
"author:StringVar wrong" only 1 result, you would think I would use the word 'wrong' more.
